# MXS Platform Support
snd-soc-mxs-objs := mxs-saif.o
snd-soc-mxs-pcm-objs := mxs-pcm.o

obj-$(CONFIG_SND_MXS_SOC) += snd-soc-mxs.o snd-soc-mxs-pcm.o

# i.MX Machine Support
snd-soc-mxs-sgtl5000-objs := mxs-sgtl5000.o
snd-soc-mxs-tlv320aic3120-objs := mxs-tlv320aic3120.o

obj-$(CONFIG_SND_SOC_MXS_SGTL5000) += snd-soc-mxs-sgtl5000.o
obj-$(CONFIG_SND_SOC_MXS_TLV320AIC3120) += snd-soc-mxs-tlv320aic3120.o
